### ISSUE TITLE
2장 상관관계

### ISSUE THREAD

**Issue by HJunPark** [rickiepark/handson-ml2#10]
Line 38에 있는
corr_matrix = housing.corr() 부분에서
housing data에 ocean_proximity 부분이 포함되어 있어,
string 데이터에 의해 pd.corr() 메서드 오류가 발생합니다.

정상적으로 작동하나요? 제가 책의 예시코드 중 데이터 전 처리를 잘못한 것인지 훑어봤는데, 딱히 누락된 부분이 없어서 확인차 말씀드립니다.

**Comment by rickiepark** [comment]
안녕하세요. 아마도 판다스 2.0을 사용하시는 것 같군요. 판다스 corr() 함수의 numeric_only 매개변수 기본값이 True였는데 2.0부터 False로 바뀌었기 때문에 발생하는 오류입니다. numeric_only=True로 지정하시고 실행하시면 될 것 같습니다. 감사합니다.

**Comment by HJunPark** [comment]
답변 감사드립니다.
