### ISSUE TITLE
2장 코드가 실행이 안됩니다. 도움 부탁드립니다.

### ISSUE THREAD

**Issue by jeaho322** [rickiepark/handson-ml2#6]
**2.6.1 훈련 세트에서 훈련하고 평가하기** 
해당 파트 첫 코드를 실행하면 다음과 같은 에러와 함께 진행이 되지 않고
지식이 없다보니 이리저리 알아봐도 해결이 안되어 여기에 도움 부탁드립니다!!
(예제코드를 돌려봐도 똑같네요, 주피터노트북에서 실행했습니다)

**= code**

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)

**= error**
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-80-7cd921ad966a> in <module>
      2 
      3 lin_reg = LinearRegression()
----> 4 lin_reg.fit(housing_prepared, housing_labels)

~\Anaconda3\envs\env_yanko\lib\site-packages\sklearn\linear_model\_base.py in fit(self, X, y, sample_weight)
    567         else:
    568             self.coef_, self._residues, self.rank_, self.singular_ = \
--> 569                 linalg.lstsq(X, y)
    570             self.coef_ = self.coef_.T
    571 

~\Anaconda3\envs\env_yanko\lib\site-packages\scipy\linalg\basic.py in lstsq(a, b, cond, overwrite_a, overwrite_b, check_finite, lapack_driver)
   1219                                                cond, False, False)
   1220         if info > 0:
-> 1221             raise LinAlgError("SVD did not converge in Linear Least Squares")
   1222         if info < 0:
   1223             raise ValueError('illegal value in %d-th argument of internal %s'

LinAlgError: SVD did not converge in Linear Least Squares

**Comment by rickiepark** [comment]
안녕하세요. 위와 같은 에러는 아마도 훈련 세트가 잘못 준비되었기 때문일 수 있습니다. 주피터 노트북에 있는 훈련 세트 전처리 과정을 모두 수행하셨나요? 특히 누락된 값을 제거하는 작업은 꼭 필요합니다. 2장의 주피터 노트북을 코랩에서 실행하면 정상적으로 수행됩니다(https://colab.research.google.com/github/rickiepark/handson-ml2/blob/master/02_end_to_end_machine_learning_project.ipynb). 작성하신 코드와 함께 비교해 보시면 좋을 것 같습니다. 감사합니다!
